### ISSUE TITLE
Wrong comment or macro?

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/rpmsg-lite#24]
What is wrong here @MichalPrincNXP? Comment or macro definition, or it is ok?

https://github.com/NXPmicro/rpmsg-lite/blob/c6b11f8ea44b049a11a35d8e08590d4532da1778/lib/include/platform/imx7ulp_m4/rpmsg_platform.h#L29
https://github.com/NXPmicro/rpmsg-lite/blob/c6b11f8ea44b049a11a35d8e08590d4532da1778/lib/include/platform/imx7ulp_m4/rpmsg_platform.h#L30

**Comment by MichalPrincNXP** [comment]
It's the inaccurate comment.

**Comment by MichalPrincNXP** [comment]
Resolved in https://github.com/nxp-mcuxpresso/rpmsg-lite/releases/tag/v5.0.0
