### ISSUE TITLE
rpmsg_lite_wait_for_link_up should be extended with timeout

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/rpmsg-lite#25]
I am suggesting to extend rpmsg_lite_wait_for_link_up with one parameter uint32_t timeoutMs and return value -> true/false
So user can insert max time to wait in ms and return true/false based on link is up or not.

**Comment by MichalPrincNXP** [comment]
Good point. Unfortunately, we already passed the feature freeze date so I can prepare the update but not be used in coming v4.0.0

**Comment by Hadatko** [comment]
No problem. Personally i don't need it. I saw NXP example where it make sense likely (app_srtm related). But generally it make sense to let user define timeout. If you would do it into this release you don't have to solve backward compatibility. I am just sharing this idea ;)

**Comment by MichalPrincNXP** [comment]
Yes, agree but the date is gone, unfortunately. Anyway, will provide this in the further release. Thanks for this idea.

**Comment by MichalPrincNXP** [comment]
Resolved in https://github.com/nxp-mcuxpresso/rpmsg-lite/releases/tag/v5.0.0
