### ISSUE TITLE
Message framentation?

### ISSUE THREAD

**Issue by infn-ke** [nxp-mcuxpresso/rpmsg-lite#26]
Does rpmsg-lite have any plans to support message fragmentation? Currently the `rpmsg_lite_send` simply drops the message if the size exceeds `RL_BUFFER_PAYLOAD_SIZE`

**Comment by MichalPrincNXP** [comment]
Hello @infn-ke , correct, the size of to-be-sent message is checked and RL_ERR_BUFF_SIZE is returned once exceeds the RL_BUFFER_PAYLOAD_SIZE. However, the fragmentation support is not planned, this is up to the application to handle. I guess, Linux rpmsg implementation does not support fragmentation either.

**Comment by escherstair** [comment]
@MichalPrincNXP looking to Linux rpmsg driver, it seems that fragmentation is not supported.
Do you know of a sucessfull fragmentation implementation on application side?

**Comment by MichalPrincNXP** [comment]
Hello @escherstair , I am not aware of a fragmentation implementation, unfortunately.
