### ISSUE TITLE
use env_rmb() is for what?

### ISSUE THREAD

**Issue by Hans5278** [nxp-mcuxpresso/rpmsg-lite#29]
I have a question about the use of _**env_rmb()**_ function in **_rpmsg_lite/virtio/virtqueue.c_** **_virtqueue_get_buffer_**. It seems that both **_used_idx_** and **_uep_** are dependent on the following code, so doesn't the program itself reorder? **_env_rmb()_** is used here to prevent reordering of which code?

**Comment by MichalPrincNXP** [comment]
Hello @Hans5278 , env_rmb() is a function that inserts read memory barrier and is mostly implemented as [dsb instruction](https://developer.arm.com/documentation/dui0489/c/arm-and-thumb-instructions/miscellaneous-instructions/dmb--dsb--and-isb), ensuring consequent data (in shared memory) read correctness (all previous memory accesses are finished). This is not related to code reordering.

**Comment by Hans5278** [comment]
>

**Comment by MichalPrincNXP** [comment]
It deals with data synchronization barrier, i.e. we need to be sure we read correct uep->id value from the shared memory. env_rmb() prevents incorrect value read while the opposite core is just writing a new value into that shared memory address. It simply waits until all previous memory transactions are done before reading that memory.

**Comment by Hans5278** [comment]
Linux virtio [https://github.com/torvalds/linux/blob/master/drivers/virtio/virtio_ring.c](url) in line 816-823 is wrtten differently than you did here, but both of you do the same thing. It makes me confused.
