### ISSUE TITLE
Documentation link is broken.

### ISSUE THREAD

**Issue by MHesham** [nxp-mcuxpresso/rpmsg-lite#3]
Browser can't find https://nxpmicro.github.io/rpmsg-lite/

**Comment by MarekNovakNXP** [comment]
It is now https://codeauroraforum.github.io/rpmsg-lite/
I will fix it.

**Comment by MazenATaha1** [comment]
@MarekNovakNXP 
Unfortunately, I have the same error.
File not found

**Comment by Hadatko** [comment]
@MazenATaha1 @MarekNovakNXP is no more participating to this project. @MichalPrincNXP do you have actuall link for newer documentation?

**Comment by Hadatko** [comment]
In readme there is still old non working link

![image](https://user-images.githubusercontent.com/13130700/207617279-16df247b-5693-4a15-8d5b-7c073f46441e.png)

**Comment by MichalPrincNXP** [comment]
Hi @MazenATaha1 , I am sorry, the project has been moved to https://github.com/nxp-mcuxpresso/rpmsg-lite recently and the correct link for the documentation is: https://nxp-mcuxpresso.github.io/rpmsg-lite/
I will update the readme.
