### ISSUE TITLE
How to use the rpmsg-lite

### ISSUE THREAD

**Issue by hwwei521** [nxp-mcuxpresso/rpmsg-lite#32]
rpmsg-lite is a very great open source software, but are there any examples of how to use it and look forward to them.

**Comment by MichalPrincNXP** [comment]
Hello @hwwei521 , you are right the information about examples is missing, thank you for pointing that. I have just added a new Examples section into the readme file on the develop branch, see https://github.com/nxp-mcuxpresso/rpmsg-lite/tree/develop 

Hope it helps.

**Comment by hwwei521** [comment]
@MichalPrincNXP Thank you very much for your reply. I alose saw the example in the SDK package.
