### ISSUE TITLE
master and remote ping each other in freertos

### ISSUE THREAD

**Issue by hwwei521** [nxp-mcuxpresso/rpmsg-lite#33]
Can rpmsg-lite call rpmsg_lite_master_init and rpmsg_lite_master_init respectively on freertos to create two tasks to ping each other?

**Comment by hwwei521** [comment]
Now we have a scenario where we want to test whether rpmsg-lite can communicate itself on the freertos side.

**Comment by MichalPrincNXP** [comment]
Hello @hwwei521 , to be honest I have not tried this way of rpmsg_lite use for the communication between FreeRTOS tasks. Thinking about the rpmsg_lite use, it could work, only the new data notification process has to be revised - inter-core interrupts have to be replaced by a mechanism that would trigger ISR on the same core, I guess.
Have you considered the use of native FreeRTOS component RTOS Message Buffers for data exchange between tasks? Or, do you focus directly on rpmsg_lite evaluation when running in two tasks on one core?
