### ISSUE TITLE
Communicating with QNX

### ISSUE THREAD

**Issue by wonk-andy** [nxp-mcuxpresso/rpmsg-lite#34]
Hello

I am working on a project using one of the i.MX8 variants.  The code running on the Cortex-M is bare metal and I have integrated rpmsg-lite into the firmware using the appropriate environment and platform files.

The Cortex-A cluster is running QNX, is there an existing library that I can include into the QNX application to be able to communicate with the Cortex-M4 or will this require a generic POSIX compliant platform to be developed for rpmsg-lite?

-Andy.

**Comment by MichalPrincNXP** [comment]
Hello @wonk-andy 
let me remind you that the qnx porting layer (rpmsg_env_qnx.c, rpmsg_env_specific.h) is part of this Github, for your reference. We recently had some QNX-based example for any imx8 device ... I will try to get more info and get back to you later ... to be honest I do not know how rpmsg_lite had been integrated into qnx os based example. Thank you.
Michal

**Comment by wonk-andy** [comment]
Hi @MichalPrincNXP 

From what I have been able to determine from speaking with the QNX distributor here in the UK, customers are using rpmsg_lite on the Cortex-M and open-amp / libmetal under QNX on the Cortex-A53.  

Unfortunately no-one seems to have pushed their libmetal implementation for QNX back into the community repo.

-Andy.

**Comment by MichalPrincNXP** [comment]
Hello @wonk-andy 
the RPMsg_Lite component was integrated via a wrapper as the librpmsg_lite-imx.so dynamic library located in BSP/src/lib/rpmsg_lite folder by NXP in 2019. It is not freely available but it could be possible to ask for that through the [NXP i.mx community](https://community.nxp.com/t5/i-MX-Processors/bd-p/imx-processors). Please, raise a question there and NXP representatives should find a way how to share that dynamic library that could help you.
Regards
Michal

**Comment by wonk-andy** [comment]
Thanks Michal

I have asked the question of the i.MX community and also our local QNX distribution channel to see if they can give me access to it.

-Andy.

**Comment by wonk-andy** [comment]
Hi @MichalPrincNXP 

The response to the [question I posted](https://community.nxp.com/t5/i-MX-Processors/RPMsg-Lite-for-QNX/td-p/1649464/jump-to/first-unread-message) to the i.MX Community was an unhelpful "we don't support QNX"

Nothing back from QNX yet either!

-Andy.

**Comment by MichalPrincNXP** [comment]
Hi @wonk-andy , I pinged ZdenekZ after your last post and it seems you will get the QNX lib through the i.MX Community soon. Can we close this issue now?
