### ISSUE TITLE
[QUESTION]: Erpc and rpmsg port to embOS

### ISSUE THREAD

**Issue by FoujanetG** [nxp-mcuxpresso/rpmsg-lite#38]
hi,
On a NXP MCU, We are using the the rpmsg_lite layer and the shared memory for the communication.
We are using the RTOS embOS of SEGGER.

Do you have the files of environnent to run this example with embOS?

Files for the porting are : rpmsg_lite/porting/environment/rpmsg_env_freertos.c and environment/freertos/rpmsg_env_specific.h

That would be great to speed up the project development.

thank you
Guillaume

**Comment by MichalPrincNXP** [comment]
Hello @FoujanetG ,
unfortunately, the embOS support in rpmsg_lite and erpc components is not planned. On the other hand doing that based on the rpmsg_env_freertos or other env. layer pattern should not be difficult. It deals with implementation of several env. specific functions only. 
Regards
Michal
