### ISSUE TITLE
[QUESTION]: Remote and master on the same core?

### ISSUE THREAD

**Issue by m42j** [nxp-mcuxpresso/rpmsg-lite#39]
Hello.

i.MX8M plus

If I fix the code would it (for testing purposes) be possible to run both master (on MU1A) and remote (on MU1B) on the same M7 core or are there hardware constraints that prevent this?

**Comment by MichalPrincNXP** [comment]
Hello @m42j 
similar to #33 , it could work, only the new data notification process has to be revised - inter-core interrupts have to be replaced by a mechanism that would trigger ISR on the same core, I guess.
Regards
Michal
