### ISSUE TITLE
[QUESTION] Environment porting unit-tests

### ISSUE THREAD

**Issue by ciscoski** [nxp-mcuxpresso/rpmsg-lite#41]
Hello all,

The documentation states that some environment porting is tested but I could not find any unit tests in the code base.
Are these unit tests available anywhere else? Would you be able to share it with the community?

Thanks

**Comment by MichalPrincNXP** [comment]
Hello @ciscoski , you are right the test code is not publicly available yet but there is a plan to do that, hope I will be able to provide it soon. Here is the list of environment layers that passed internal testing:
  * rpmsg_env_bm.c 
  * rpmsg_env_freertos.c 
  * rpmsg_env_xos.c 
  * rpmsg_env_threadx.c 

Regards
Michal

**Comment by ciscoski** [comment]
Nice. Thanks
